---
- hosts: app
  become: true
  tasks:
    - name: Install ngnix
      yum:
        name: httpd
        state: present

    - name: Copy application code
      copy:
        src: /opt/jenkins/workspace/sample build job/app
        dest: /var/www/html/

    - name: Restart web server
      service:
        name: httpd
        state: restarted

